variables:
  - group: Pondrop-Mobile-Dev
  
jobs:
  - job: Mobile
    pool:
      vmImage: 'macOS-latest'
    steps:

      - task: JavaToolInstaller@0
        displayName: 'Install Java 11'
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: FlutterInstall@0
        displayName: 'Install Flutter'
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        displayName: "Android Flutter Build"
        inputs:
          target: 'aab'
          projectDirectory: '.'
          buildNumber: '$(Build.BuildId)'
          buildName: '1.0.$(Build.BuildId)'
          entryPoint: 'lib/main.dart'
          extraArgs: '--no-tree-shake-icons'
          
      # - task: AndroidSigning@3
      #   displayName: "Android Signing"
      #   inputs:
      #     apkFiles: '**/*.aab'
      #     apksignerKeystoreFile: key.jks 
      #     apksignerKeystorePassword: $(androidKeystorePassword)
      #     apksignerKeystoreAlias: '$(androidKeystoreAlias)'
      #     apksignerKeyPassword: '$(androidKeystorePassword)'
      #     apksignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'

      - task: ios-bundle-version@1
        displayName: 'Set iOS version numbers'
        inputs:
          sourcePath: 'ios/Runner/Info.plist'
          versionCodeOption: 'buildid'
          versionCode: '$(Build.BuildId)'
          printFile: true

      - task: FlutterBuild@0
        displayName: "iOS Flutter Build"
        inputs:
          target: 'ios'
          projectDirectory: '.'
          entryPoint: 'lib/main.dart'
          iosCodesign: false
          extraArgs: '--no-tree-shake-icons'

      - task: FlutterTest@0
        displayName: "Run Flutter Tests"
        inputs:
          projectDirectory: '.'           
            
      - task: CopyFiles@2
        displayName: 'Copy Android build package'
        inputs:
          contents: '**/*.aab'
          targetFolder: '$(build.artifactStagingDirectory)'
          OverWrite: true   

      - task: InstallAppleCertificate@2
        displayName: "Install Apple p12 cert"
        inputs:
          certSecureFile: "pondrop.p12"
          certPwd: $(p12Password)
          keychain: "temp"
          deleteCert: true
          deleteCustomKeychain: false
              
      - task: InstallAppleProvisioningProfile@1
        displayName: "Install iOS AdHoc Provisioning Profile"
        inputs:
          provisioningProfileLocation: "secureFiles"
          provProfileSecureFile: "adhoc.mobileprovision"
          removeProfile: true

      - task: InstallAppleProvisioningProfile@1
        displayName: "Install iOS Distribution Provisioning Profile"
        inputs:
          provisioningProfileLocation: "secureFiles"
          provProfileSecureFile: "distribution.mobileprovision"
          removeProfile: true
          
      - task: Xcode@5
        displayName: "Build iOS Ad-Hoc"
        inputs:
          actions: "build"
          xcWorkspacePath: "**/Runner.xcworkspace"
          scheme: "Runner"
          sdk: "iphoneos"
          configuration: "release"
          packageApp: true
          signingOption: "manual"
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          provisioningProfileUuid: '$(adhocProfileUuid)'
            
      - task: CopyFiles@2
        displayName: 'Copy Ad-Hoc iOS build package'
        inputs:
          contents: '**/*.ipa'
          targetFolder: '$(build.artifactStagingDirectory)/adhoc'
          OverWrite: true
            
      - task: Xcode@5
        displayName: "Build iOS Distribution"
        inputs:
          actions: "build"
          xcWorkspacePath: "**/Runner.xcworkspace"
          scheme: "Runner"
          sdk: "iphoneos"
          configuration: "release"
          packageApp: true
          signingOption: "manual"
          signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
          provisioningProfileUuid: '$(distProfileUuid)'
                    
      - task: CopyFiles@2
        displayName: 'Copy Distribution iOS build package'
        inputs:
          contents: '**/*.ipa'
          targetFolder: '$(build.artifactStagingDirectory)/distribution'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'drop'